### ISSUE TITLE
Can you add Root Packages ?

### ISSUE THREAD

**Issue by Deathlive** [xeffyr/termux-x-repository#2]
Can you add here packages Iptables, tshark... The entire package of Termux packages so that can download them via Apt → [Termu Root Packages](https://github.com/termux/termux-root-packages)

**Comment by xeffyr** [comment]
1. This is a repository for X/GUI packages (such as Openbox) and dependencies of them so command-line only packages won't be added.
2. iptables is part of Android. Look at /system/bin/iptables. Some features may not be available because of kernel configuration.
3. When GTK will be available, graphics-enabled version of wireshark will be added.
